version: "3.9"
services:
  # lab:
  #   build: ./docker/lab
  #   image: jupyterlab
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./notebooks:/home/jovyan/work/source
  #     - ./exchange:/home/jovyan/work/exchange
  #     - ./docker/lab/nbgrader_config.py:/etc/jupyter/nbgrader_config.py
  hub:
    build: ./docker/hub
    image: jupyterhub
    hostname: jupyterhub
    ports:
      - "8000:8000"
    volumes:
      - ./docker/hub/jupyterhub_config.py:/etc/jupyterhub/jupyterhub_config.py
      - ./data:/srv/jupyterhub/data
      - ./test:/srv/ngshare/:rw
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jupyterhub-network
    environment:
      DOCKER_NETWORK_NAME: jupyterhub-network
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work
      SINGLEUSER_IMAGE: jupyterlab-singleuser
      IP_ADDRESS: "172.22.0.2"

volumes:
  jupyterhub_data:

networks:
  jupyterhub-network:
    name: jupyterhub-network