version: "3.9"
services:
  hub:
    build: ./hub
    image: jupyterhub
    hostname: jupyterhub
    ports:
      - "8000:8000"
    volumes:
      - ./hub/jupyterhub_config.py:/etc/jupyterhub/jupyterhub_config.py
      # - ./exchange:/opt/exchange
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/srv/jupyterhub/data
    networks:
      - jupyterhub-network
    environment:
      DOCKER_NETWORK_NAME: jupyterhub-network
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work
      SINGLEUSER_IMAGE: jupyterlab-singleuser

volumes:
  jupyterhub_data:

networks:
  jupyterhub-network:
    name: jupyterhub-network