version: "3.9"
services:
  lab:
    image: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/opt/source
      - ./exchange:/opt/exchange
      - ./config/lab:/etc/jupyter
    working_dir: /opt
  hub:
    image: jupyterhub/jupyterhub
    ports:
      - "8000:8000"
    volumes:
      - ./config/hub:/etc/jupyterhub
    working_dir: /opt