version: "3.9"
services:
  jupyterlab:
    build: .
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/opt/notebooks
      - ./exchange:/opt/exchange
      - ./config:/etc/jupyter