version: "3.9"
services:
  app:
    image: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/opt/source
      - ./exchange:/opt/exchange
      - ./config:/etc/jupyter
      - ./notebooks_backup:/opt/notebooks_backup